![New York City schoolbus](schoolbus.jpg)

Photo by [Jannis Lucas](https://unsplash.com/@jannis_lucas) on [Unsplash](https://unsplash.com).
<br>

Every year, American high school students take SATs, which are standardized tests intended to measure literacy, numeracy, and writing skills. There are three sections - reading, math, and writing, each with a **maximum score of 800 points**. These tests are extremely important for students and colleges, as they play a pivotal role in the admissions process.

Analyzing the performance of schools is important for a variety of stakeholders, including policy and education professionals, researchers, government, and even parents considering which school their children should attend. 

You have been provided with a dataset called `schools.csv`, which is previewed below.

You have been tasked with answering three key questions about New York City (NYC) public school SAT performance.

In [1]:
# Re-run this cell 
import pandas as pd

# Read in the data
schools = pd.read_csv("schools.csv")

# Preview the data
schools.head()

# Start coding here...
# Add as many cells as you like...

,school_name,borough,building_code,average_math,average_reading,average_writing,percent_tested
0,"New Explorations into Science, Technology and ...",Manhattan,M022,657,601,601,NaN
1,Essex Street Academy,Manhattan,M445,395,411,387,78.9
2,Lower Manhattan Arts Academy,Manhattan,M445,418,428,415,65.1
3,High School for Dual Language and Asian Studies,Manhattan,M445,613,453,463,95.9
4,Henry Street School for International Studies,Manhattan,M056,410,406,381,59.7

# Finding schools with the best math scores
Which NYC schools have the best math results?
    The best math results are at least 80% of the *maximum possible score of 800* for math.
    Save your results in a pandas DataFrame called best_math_schools, including "school_name" and "average_math" columns, sorted by "average_math" in descending order.

In [ ]:
import numpy as np
np.sort(schools['average_math'].unique())

array([317, 319, 326, 332, 340, 344, 345, 350, 355, 356, 357, 358, 360,
       361, 362, 363, 364, 365, 366, 367, 369, 370, 371, 372, 374, 375,
       376, 377, 378, 379, 380, 381, 382, 383, 384, 385, 386, 387, 389,
       390, 391, 392, 393, 394, 395, 396, 397, 398, 399, 400, 401, 402,
       403, 404, 405, 406, 407, 408, 409, 410, 411, 413, 415, 416, 417,
       418, 419, 420, 421, 422, 423, 424, 425, 426, 427, 428, 429, 430,
       431, 432, 433, 434, 435, 436, 437, 438, 439, 441, 442, 443, 444,
       445, 446, 448, 451, 452, 453, 454, 455, 458, 459, 460, 463, 464,
       466, 467, 468, 469, 474, 475, 476, 477, 478, 479, 481, 483, 484,
       485, 487, 488, 489, 490, 492, 494, 495, 496, 500, 501, 502, 503,
       504, 505, 511, 512, 513, 514, 516, 517, 518, 521, 522, 523, 524,
       525, 534, 536, 550, 553, 556, 560, 562, 563, 577, 581, 583, 588,
       592, 595, 613, 625, 631, 633, 634, 641, 657, 669, 680, 682, 683,
       701, 711, 714, 754])

In [11]:
# Get the benchmark math score that is at least 80% (out of 800)
benchmark_math_score = .8 * 800
print(benchmark_math_score)

640.0

In [13]:
# create a new dataframe called 'best_math_schools' which includes 'school_name' and 'average_math' columns, 
# sorted by 'average_math' in descending order
best_schools = schools[schools['average_math'] >= benchmark_math_score]
display(best_schools)

,school_name,borough,building_code,average_math,average_reading,average_writing,percent_tested
0,"New Explorations into Science, Technology and ...",Manhattan,M022,657,601,601,NaN
45,Eleanor Roosevelt High School,Manhattan,M855,641,617,631,86.0
68,"High School for Mathematics, Science, and Engi...",Manhattan,M812,683,610,596,92.6
88,Stuyvesant High School,Manhattan,M477,754,697,693,97.4
93,Staten Island Technical High School,Staten Island,R440,711,660,670,99.7
170,Bronx High School of Science,Bronx,X445,714,660,667,97.0
174,High School of American Studies at Lehman College,Bronx,X905,669,672,672,91.8
280,Brooklyn Technical High School,Brooklyn,K430,682,608,606,95.5
333,Townsend Harris High School,Queens,Q515,680,640,661,97.1
365,Queens High School for the Sciences at York Co...,Queens,Q774,701,621,625,97.9

In [15]:
best_math_schools = best_schools[['school_name', 'average_math']]\
    .sort_values(by='average_math', ascending=False)

In [16]:
display(best_math_schools)

                                           school_name  average_math
88                              Stuyvesant High School           754
170                       Bronx High School of Science           714
93                 Staten Island Technical High School           711
365  Queens High School for the Sciences at York Co...           701
68   High School for Mathematics, Science, and Engi...           683
280                     Brooklyn Technical High School           682
333                        Townsend Harris High School           680
174  High School of American Studies at Lehman College           669
0    New Explorations into Science, Technology and ...           657
45                       Eleanor Roosevelt High School           641

# Identifying the top 10 performing schools
What are the top 10 performing schools based on the combined SAT scores?
    Save your results as a pandas DataFrame called top_10_schools containing the "school_name" and a new column named "total_SAT", with results ordered by "total_SAT" in descending order ("total_SAT" being the sum of math, reading, and writing scores).

In [17]:
display(schools)

,school_name,borough,building_code,average_math,average_reading,average_writing,percent_tested
0,"New Explorations into Science, Technology and ...",Manhattan,M022,657,601,601,NaN
1,Essex Street Academy,Manhattan,M445,395,411,387,78.9
2,Lower Manhattan Arts Academy,Manhattan,M445,418,428,415,65.1
3,High School for Dual Language and Asian Studies,Manhattan,M445,613,453,463,95.9
4,Henry Street School for International Studies,Manhattan,M056,410,406,381,59.7
...,...,...,...,...,...,...,...
370,"Queens High School for Information, Research, ...",Queens,Q465,372,362,352,44.6
371,Rockaway Park High School for Environmental Su...,Queens,Q410,357,381,376,38.5
372,Channel View School for Research,Queens,Q410,427,430,423,76.6
373,Rockaway Collegiate High School,Queens,Q410,399,403,405,46.5
374,Scholars' Academy,Queens,Q180,588,560,568,99.2

In [21]:
# Create a new column called 'total_SAT' that will add 'average_math', 
# 'average_reading','average_writing' scores 
schools['total_SAT'] = schools['average_math'] + schools['average_reading'] + schools['average_writing']
display(schools)

,school_name,borough,building_code,average_math,average_reading,average_writing,percent_tested,total_SAT
0,"New Explorations into Science, Technology and ...",Manhattan,M022,657,601,601,NaN,1859
1,Essex Street Academy,Manhattan,M445,395,411,387,78.9,1193
2,Lower Manhattan Arts Academy,Manhattan,M445,418,428,415,65.1,1261
3,High School for Dual Language and Asian Studies,Manhattan,M445,613,453,463,95.9,1529
4,Henry Street School for International Studies,Manhattan,M056,410,406,381,59.7,1197
...,...,...,...,...,...,...,...,...
370,"Queens High School for Information, Research, ...",Queens,Q465,372,362,352,44.6,1086
371,Rockaway Park High School for Environmental Su...,Queens,Q410,357,381,376,38.5,1114
372,Channel View School for Research,Queens,Q410,427,430,423,76.6,1280
373,Rockaway Collegiate High School,Queens,Q410,399,403,405,46.5,1207
374,Scholars' Academy,Queens,Q180,588,560,568,99.2,1716

In [23]:
schools

,school_name,borough,building_code,average_math,average_reading,average_writing,percent_tested,total_SAT
0,"New Explorations into Science, Technology and ...",Manhattan,M022,657,601,601,NaN,1859
1,Essex Street Academy,Manhattan,M445,395,411,387,78.9,1193
2,Lower Manhattan Arts Academy,Manhattan,M445,418,428,415,65.1,1261
3,High School for Dual Language and Asian Studies,Manhattan,M445,613,453,463,95.9,1529
4,Henry Street School for International Studies,Manhattan,M056,410,406,381,59.7,1197
...,...,...,...,...,...,...,...,...
370,"Queens High School for Information, Research, ...",Queens,Q465,372,362,352,44.6,1086
371,Rockaway Park High School for Environmental Su...,Queens,Q410,357,381,376,38.5,1114
372,Channel View School for Research,Queens,Q410,427,430,423,76.6,1280
373,Rockaway Collegiate High School,Queens,Q410,399,403,405,46.5,1207
374,Scholars' Academy,Queens,Q180,588,560,568,99.2,1716

In [ ]:
# Create a dataframe called 'top_10_schools' containing the 'school_name' and 'total_SAT',
# with results ordered by "total_SAT" in descending order
top_10_schools = schools[['school_name', 'total_SAT']]\
    .sort_values(by='total_SAT', ascending=False)\
    .head(10)

In [28]:
display(top_10_schools)

                                           school_name  total_SAT
88                              Stuyvesant High School       2144
170                       Bronx High School of Science       2041
93                 Staten Island Technical High School       2041
174  High School of American Studies at Lehman College       2013
333                        Townsend Harris High School       1981
365  Queens High School for the Sciences at York Co...       1947
5                       Bard High School Early College       1914
280                     Brooklyn Technical High School       1896
45                       Eleanor Roosevelt High School       1889
68   High School for Mathematics, Science, and Engi...       1889

# Locating the NYC borough with the largest standard deviation in SAT performance
Which single borough has the largest standard deviation in the combined SAT score?

    Save your results as a pandas DataFrame called 'largest_std_dev'.
    The DataFrame should contain one row, with:
    "borough" - the name of the NYC borough with the largest standard deviation of "total_SAT".
    "num_schools" - the number of schools in the borough.
    "average_SAT" - the mean of "total_SAT".
    "std_SAT" - the standard deviation of "total_SAT".
    Round all numeric values to two decimal places.

In [29]:
schools

,school_name,borough,building_code,average_math,average_reading,average_writing,percent_tested,total_SAT
0,"New Explorations into Science, Technology and ...",Manhattan,M022,657,601,601,NaN,1859
1,Essex Street Academy,Manhattan,M445,395,411,387,78.9,1193
2,Lower Manhattan Arts Academy,Manhattan,M445,418,428,415,65.1,1261
3,High School for Dual Language and Asian Studies,Manhattan,M445,613,453,463,95.9,1529
4,Henry Street School for International Studies,Manhattan,M056,410,406,381,59.7,1197
...,...,...,...,...,...,...,...,...
370,"Queens High School for Information, Research, ...",Queens,Q465,372,362,352,44.6,1086
371,Rockaway Park High School for Environmental Su...,Queens,Q410,357,381,376,38.5,1114
372,Channel View School for Research,Queens,Q410,427,430,423,76.6,1280
373,Rockaway Collegiate High School,Queens,Q410,399,403,405,46.5,1207
374,Scholars' Academy,Queens,Q180,588,560,568,99.2,1716

## Grouping the data by borough
 Find the count of schools, mean and standard deviation of 'total_SAT'

In [ ]:
schools.groupby('borough')['total_SAT'].agg(['count','mean','std']).round(2)

               count     mean     std
borough
Bronx             98  1202.72  150.39
Brooklyn         109  1230.26  154.87
Manhattan         89  1340.13  230.29
Queens            69  1345.48  195.25
Staten Island     10  1439.00  222.30